# Generated by Django 5.0.4 on 2024-07-10 14:56

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client_Statut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Client_Statut_ID",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ]
                    ),
                ),
                ("Statut_Description", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "Client_Statut",
            },
        ),
        migrations.AlterField(
            model_name="client_discounts",
            name="Stamp_Date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 10, 14, 56, 39, 30641, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
