# Generated by Django 5.0.4 on 2024-07-09 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_client_statut_alter_client_discounts_stamp_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client_discounts",
            name="Stamp_Date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 9, 15, 23, 0, 918585, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
