# Generated by Django 5.0.4 on 2024-07-18 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_client_statut"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="route_users",
            unique_together={("Route_ID", "User_Code")},
        ),
        migrations.RemoveField(
            model_name="routes",
            name="CreateBy",
        ),
        migrations.RemoveField(
            model_name="routes",
            name="Org_ID",
        ),
        migrations.RemoveField(
            model_name="routes",
            name="user_code",
        ),
        migrations.AlterField(
            model_name="route_users",
            name="User_Code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.internaluser"
            ),
        ),
        migrations.RemoveField(
            model_name="route_users",
            name="Org_ID",
        ),
    ]
