# Generated by Django 5.0.4 on 2024-07-10 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_client_statut_alter_client_discounts_stamp_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clients",
            name="id",
        ),
        migrations.AlterField(
            model_name="client_discounts",
            name="Stamp_Date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 10, 14, 59, 29, 457089, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="clients",
            name="Client_Code",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
