# Generated by Django 5.0.4 on 2024-07-08 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_client_statut_client_statut_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client_discounts",
            name="Month",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="client_discounts",
            name="Years",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1990),
                    django.core.validators.MaxValueValidator(2030),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="client_target",
            name="Month",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="client_target",
            name="years",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1990),
                    django.core.validators.MaxValueValidator(2030),
                ]
            ),
        ),
    ]
