# Generated by Django 5.0.4 on 2024-07-18 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_route_users_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="regions",
            table="Regions",
        ),
    ]
