# Generated by Django 5.0.4 on 2024-07-18 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_regions_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regions",
            name="Stamp_Date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="routes",
            name="Branch_Code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="routes",
            name="Region_Code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="routes",
            name="Route_Alt_Description",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="routes",
            name="Route_Description",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="routes",
            name="Stamp_Date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
