# Generated by Django 5.0.4 on 2024-07-10 15:24

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_clients_allow_check_clients_allow_pdc_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clients",
            name="Allow_Check",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Allow_PDC",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Area_Of_Business_Code",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Channel_Code",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="City_Code",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Classification_Code",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Client_Type_ID",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Collection_Type",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Currency_Code",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Fax_Number",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Grace_Period",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Invoice_Limit",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Invoice_Settlement",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="IsFromERP",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Is_Dummy",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Is_From_Census",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Is_Taxable",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Latitude",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Longitude",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Number_Of_Outlets",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Org_ID",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Parent_Client_Code",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Price_List_Code",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Price_List_Code2",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Region_Code",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Return_Price_List_Code",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Sq_Meter_Area",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Stamp_Date",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Tax_Code",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="User_Code",
        ),
        migrations.AlterField(
            model_name="client_discounts",
            name="Stamp_Date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 10, 15, 24, 22, 903383, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="clients",
            name="Address",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="clients",
            name="Alt_Address",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="clients",
            name="Area_Code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="clients",
            name="Barcode",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="clients",
            name="Client_Alt_Description",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="clients",
            name="Client_Description",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="clients",
            name="Client_Status_ID",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(2),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="clients",
            name="Contact_Person",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="clients",
            name="Payment_Term_Code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="clients",
            name="Phone_Number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterModelTable(
            name="clients",
            table="Clients",
        ),
        migrations.CreateModel(
            name="Clients_Info",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Org_ID", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "Channel_Code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "Area_Of_Business_Code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("City_Code", models.CharField(blank=True, max_length=50, null=True)),
                ("Is_Dummy", models.IntegerField(blank=True, null=True)),
                ("Fax_Number", models.CharField(blank=True, max_length=50, null=True)),
                ("Longitude", models.CharField(blank=True, max_length=50, null=True)),
                ("Latitude", models.CharField(blank=True, max_length=50, null=True)),
                ("Tax_Code", models.CharField(blank=True, max_length=50, null=True)),
                ("IsFromERP", models.IntegerField(blank=True, null=True)),
                (
                    "Currency_Code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "Sq_Meter_Area",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("Collection_Type", models.IntegerField(blank=True, null=True)),
                ("Client_Type_ID", models.IntegerField(blank=True, null=True)),
                ("Stamp_Date", models.DateTimeField(blank=True, null=True)),
                ("User_Code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "Parent_Client_Code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "Price_List_Code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("Is_From_Census", models.IntegerField(blank=True, null=True)),
                (
                    "Price_List_Code2",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "Return_Price_List_Code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("Grace_Period", models.IntegerField(blank=True, null=True)),
                ("Is_Taxable", models.IntegerField(blank=True, null=True)),
                (
                    "Invoice_Limit",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("Invoice_Settlement", models.IntegerField(blank=True, null=True)),
                ("Allow_PDC", models.IntegerField(blank=True, null=True)),
                ("Allow_Check", models.IntegerField(blank=True, null=True)),
                ("Number_Of_Outlets", models.IntegerField(blank=True, null=True)),
                (
                    "Classification_Code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "Client_Code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients_info",
                        to="users.clients",
                    ),
                ),
                (
                    "Region_Code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.regions",
                    ),
                ),
            ],
            options={
                "db_table": "Clients_Info",
            },
        ),
    ]
