# Generated by Django 5.0.4 on 2024-07-18 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_regions_stamp_date_alter_routes_branch_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clients",
            name="Has_Route",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clients",
            name="Route_ID",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.routes",
            ),
        ),
    ]
