# Generated by Django 5.0.4 on 2024-07-18 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_clients_has_route_clients_route_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="Route_ID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.routes",
            ),
        ),
    ]
