# Generated by Django 5.0.4 on 2024-07-11 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_rename_client_code_clients_info_client_codes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client_discounts",
            name="Client_Code",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="client_discounts",
            name="Stamp_Date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 11, 11, 19, 5, 431662, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="client_target",
            name="Client_Code",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="clients",
            name="Phone_Number",
            field=models.IntegerField(),
        ),
    ]
