# Generated by Django 5.0.4 on 2024-07-11 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_client_discounts_client_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client_discounts",
            name="Stamp_Date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
