# Generated by Django 5.0.4 on 2024-07-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_clients_route_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGroupe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Code_groupe", models.CharField(max_length=50)),
                ("Groupe_description", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "UserGroupe",
            },
        ),
    ]
