# Generated by Django 5.0.4 on 2024-07-23 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_usergroupe"),
    ]

    operations = [
        migrations.AddField(
            model_name="clients",
            name="Channel_description",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.channels",
            ),
        ),
        migrations.AddField(
            model_name="clients",
            name="Salesman",
            field=models.CharField(blank=True, default="N/A", max_length=100),
        ),
        migrations.AddField(
            model_name="internaluser",
            name="ParentDescription",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="internaluser",
            name="Route_ID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.routes",
            ),
        ),
        migrations.AddField(
            model_name="internaluser",
            name="UserType",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="routes",
            name="RVSCode",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="routes",
            name="RVSDescription",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.DeleteModel(
            name="Route_Users",
        ),
    ]
