# Generated by Django 5.0.7 on 2024-07-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_statut_description_client_statut_sstatut_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_statut',
            old_name='sStatut_Description',
            new_name='Statut_Description',
        ),
    ]
