# Generated by Django 5.0.4 on 2024-07-25 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_clients_channel_description_clients_salesman_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_serial", models.CharField(max_length=100, unique=True)),
                ("device_name", models.CharField(max_length=100)),
                ("device_status", models.CharField(max_length=100)),
                ("type", models.CharField(default="HHT", max_length=100)),
                (
                    "Route_ID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.routes",
                    ),
                ),
                (
                    "UserCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.internaluser",
                    ),
                ),
            ],
        ),
    ]
