# Generated by Django 5.0.4 on 2024-07-31 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_produit_altproduitdescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promoitembasketheaders",
            name="last_updated_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
