# Generated by Django 5.0.4 on 2024-07-31 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_promoitembasketheaders_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promoheaders",
            name="achievement",
        ),
        migrations.RemoveField(
            model_name="promoheaders",
            name="parent_id",
        ),
        migrations.RemoveField(
            model_name="promoheaders",
            name="target_value",
        ),
        migrations.AddField(
            model_name="promoheaders",
            name="basket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotions",
                to="users.promoitembasketheaders",
            ),
        ),
        migrations.AlterField(
            model_name="promoheaders",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="promoheaders",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="promoheaders",
            name="promotion_apply",
            field=models.CharField(
                choices=[
                    ("ISELL", "ISELL"),
                    ("E-Ordering", "E-Ordering"),
                    ("Retail", "Retail"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="promoheaders",
            name="promotion_description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="promoheaders",
            name="promotion_type",
            field=models.CharField(
                choices=[
                    ("Trade Sales", "Trade Sales"),
                    ("Consumer Sales", "Consumer Sales"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="promoheaders",
            name="start_date",
            field=models.DateField(),
        ),
    ]
