# Generated by Django 5.0.4 on 2024-08-01 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_remove_promoheaders_achievement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promoheaders",
            name="basket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promo_headers",
                to="users.promoitembasketheaders",
            ),
        ),
        migrations.CreateModel(
            name="PromoDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_buy", models.IntegerField()),
                (
                    "types_buy",
                    models.CharField(
                        choices=[
                            ("Amount", "Amount"),
                            ("Caisse", "Caisse"),
                            ("Cartouche", "Cartouche"),
                            ("Paquet", "Paquet"),
                        ],
                        max_length=50,
                    ),
                ),
                ("quantity_get", models.IntegerField()),
                (
                    "types_get",
                    models.CharField(
                        choices=[
                            ("Pourcentage", "Pourcentage"),
                            ("Cutoff Price", "Cutoff Price"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "basket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_details",
                        to="users.promoitembasketheaders",
                    ),
                ),
                (
                    "promotion_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo",
                        to="users.promoheaders",
                    ),
                ),
            ],
            options={
                "db_table": "Promo_Details",
            },
        ),
    ]
