# Generated by Django 5.0.4 on 2024-08-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_promoheaders_basket_promodetails"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promoheaders",
            name="basket",
        ),
    ]
