# Generated by Django 5.0.4 on 2024-08-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_remove_promoheaders_basket"),
    ]

    operations = [
        migrations.AddField(
            model_name="promoheaders",
            name="clients",
            field=models.ManyToManyField(
                blank=True, related_name="promotions", to="users.clients"
            ),
        ),
        migrations.AddField(
            model_name="promoheaders",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="promotions", to="users.internaluser"
            ),
        ),
    ]
