# Generated by Django 5.0.4 on 2024-08-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_promoheaders_clients_promoheaders_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promoheaders",
            name="clients",
        ),
        migrations.RemoveField(
            model_name="promoheaders",
            name="users",
        ),
        migrations.AddField(
            model_name="clients",
            name="promotions",
            field=models.ManyToManyField(
                blank=True, related_name="clients", to="users.promoheaders"
            ),
        ),
        migrations.AddField(
            model_name="internaluser",
            name="promotions",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="users.promoheaders"
            ),
        ),
    ]
