# Generated by Django 5.0.4 on 2024-08-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_usergroupe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="promotions",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="clients", to="users.promoheaders"
            ),
        ),
    ]
