# Generated by Django 5.0.4 on 2024-08-19 08:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_alter_clients_promotions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client_target",
            name="Stamp_Date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
